# Project language
language: php

# Allows use container-based infrastructure
sudo: false

# Start mysql service
services:
  - mysql

# Cache composer packages so "composer install" is faster
cache:
  directories:
    - $HOME/.composer/cache/files

# Matrix to test in every php version
matrix:
  fast_finish: true
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1
    # Use the newer stack for HHVM as HHVM does not support Precise anymore since a long time and so Precise has an outdated version
    - php: hhvm
      sudo: required
      dist: trusty
      group: edge
  allow_failures:
    - php: hhvm

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi  
  - cp app/config/parameters.yml.dist app/config/parameters.yml
  - composer self-update

# Install composer dependencies
install:
  - composer install

# Run script
script:
  - ./bin/phpunit -c app
