<?php

namespace FBN\GuideBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BookmarkRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BookmarkRepository extends EntityRepository
{
    public function getBookmarkByEntityId($userId, $entity, $entityId)
    {
        $qb = $this->createQueryBuilder('f')
                    ->where('f.user = :user_id')
                    ->setParameter('user_id', $userId)
                    ->andwhere('f.'.$entity.' = :entity_id')
                    ->setParameter('entity_id', $entityId);

        return $qb->getQuery()
            ->getOneOrNullResult();
    }

    public function getBookmarksByEntity($userId, $entity)
    {
        // Using join to only take data with correspondances
        $qb = $this->createQueryBuilder('f')
                    ->where('f.user = :user_id')
                    ->setParameter('user_id', $userId)
                   ->join('f.'.$entity, 'fr')
                   ->addSelect('fr');

        return $qb->getQuery()
            ->getArrayResult();
    }
}
