<?php

namespace FBN\GuideBundle\Entity;

/**
 * CoordinatesFRCityRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinatesFRCityRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAscendingSortedCitiesQueryBuilder()
    {
        return $this
            ->createQueryBuilder('cfrc')
            ->orderBy('cfrc.city', 'ASC')
        ;
    }
}
