<?php

namespace FBN\GuideBundle\Entity;

/**
 * CoordinatesFRAreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinatesFRAreaRepository extends \Doctrine\ORM\EntityRepository
{
}
