<?php

namespace FBN\GuideBundle\Entity;

/**
 * CoordinatesFRDeptRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinatesFRDeptRepository extends \Doctrine\ORM\EntityRepository
{
}
