<?php

namespace FBN\GuideBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CoordonneesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordonneesRepository extends EntityRepository
{

	public function joinCoord(\Doctrine\ORM\QueryBuilder $qb)
	{
	   	$qb->leftJoin('c.coordonneesFR', 'cfr')
	       ->addSelect('cfr')	
	       ->leftJoin('cfr.coordinatesFRLane', 'cfrv')
	       ->addSelect('cfrv')
	       ->leftJoin('c.coordonneesPays', 'cp')
	       ->addSelect('cp');

	   	return $qb; 
	}

}
