<?php

namespace FBN\GuideBundle\Entity;

/**
 * CoordinatesCountryRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoordinatesCountryRepository extends \Doctrine\ORM\EntityRepository
{
}
