<?php

namespace FBN\GuideBundle\Entity;

/**
 * ImageRestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRestaurantRepository extends \Doctrine\ORM\EntityRepository
{
}
