<?php

namespace FBN\GuideBundle\Entity;

/**
 * ImageTutorialRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageTutorialRepository extends \Doctrine\ORM\EntityRepository
{
}
