<?php

namespace FBN\GuideBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * InfoRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoRepository extends EntityRepository
{
    public function getArticlesImages($first = 0, $limit = Article::NUM_ITEMS)
    {
        $qb = $this->createQueryBuilder('i')
            ->orderBy('i.datePublication', 'DESC')
            ->andWhere('i.publication = :publication')
            ->setParameter('publication', true);

        $query = $qb->getQuery();

        $query->setFirstResult($first)
            ->setMaxResults($limit);

        return $query->getResult();
    }
}
