<?php

namespace FBN\GuideBundle\Entity;

/**
 * RestaurantPriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantPriceRepository extends \Doctrine\ORM\EntityRepository
{
}
