<?php

namespace FBN\GuideBundle\Entity;

/**
 * RestaurantBonusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantBonusRepository extends \Doctrine\ORM\EntityRepository
{
}
