<?php

namespace FBN\GuideBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;


/**
 * RestaurantRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends EntityRepository
{
    public function getArticlesImages($first = 0, $limit = Article::NUM_ITEMS)
    {
        $qb = $this->createQueryBuilder('r')
                   ->leftJoin('r.image', 'i')
                   ->addSelect('i')
                   ->orderBy('r.datePublication', 'DESC')
                    ->where('r.publication = :publication')
                    ->setParameter('publication', 1);

        $query = $qb->getQuery();

        $query->setFirstResult($first)
              ->setMaxResults($limit);

        return new Paginator($query);
    }

    public function getRestaurant($slug)
    {
        $qb = $this->createQueryBuilder('r')
                   ->leftJoin('r.image', 'i')
                   ->addSelect('i')
                   ->leftJoin('r.restaurantPrice', 'rp')
                   ->addSelect('rp')
                   ->leftJoin('r.restaurantStyle', 'rs')
                   ->addSelect('rs')
                   ->leftJoin('r.restaurantBonus', 'rb')
                   ->addSelect('rb')
                   ->leftJoin('r.coordonnees', 'c')
                   ->addSelect('c')
                   ->leftJoin('r.shop', 'rc')
                   ->addSelect('rc')
                   ->where('r.slug = :slug')
                   ->setParameter('slug', $slug);

        $cr = $this->_em
                    ->getRepository('FBNGuideBundle:Coordonnees');

        $qb = $cr->joinCoord($qb);

        return $qb->getQuery()
                  ->getOneOrNullResult();
    }
}
