<?php

namespace FBN\GuideBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ShopRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends EntityRepository
{
    public function getArticlesImages($first = 0, $limit = Shop::NUM_ITEMS)
    {
        $qb = $this->createQueryBuilder('s')
            ->orderBy('s.datePublication', 'DESC')
            ->andWhere('s.publication = :publication')
            ->setParameter('publication', true);

        $query = $qb->getQuery();

        $query->setFirstResult($first)
            ->setMaxResults($limit);

        $shops = $query->getResult();

        $restaurantShops = $this->_em
            ->getRepository('FBNGuideBundle:Restaurant')
            ->getRestaurantShops();

        $allShops = array();
        $allShops = array_merge_recursive($shops, $restaurantShops);
        uasort($allShops, 'FBN\GuideBundle\Utils\Entity::compareDate');
        $allShops = array_slice($allShops, $first, $limit);

        return $allShops;
    }

    public function getShop($slug)
    {
        $qb = $this->createQueryBuilder('s')
            ->leftJoin('s.coordinates', 'c')
            ->addSelect('c')
            ->andWhere('s.publication = :publication')
            ->setParameter('publication', true)
            ->andWhere('s.slug = :slug')
            ->setParameter('slug', $slug);

        $cr = $this->_em
            ->getRepository('FBNGuideBundle:Coordinates');

        $qb = $cr->joinCoord($qb);

        return $qb->getQuery()
            ->getOneOrNullResult();
    }
}
