<?php

namespace FBN\GuideBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ShopRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopRepository extends EntityRepository
{
    public function getArticlesImages($first = 0, $limit = Article::NUM_ITEMS)
    {
        $qb = $this->createQueryBuilder('cav')
                   ->leftJoin('cav.image', 'i')
                   ->addSelect('i')
                   ->orderBy('cav.datePublication', 'DESC')
                    ->where('cav.publication = :publication')
                    ->setParameter('publication', 1);

        $query = $qb->getQuery();

        $query->setFirstResult($first)
              ->setMaxResults($limit);

        return new Paginator($query);
    }

    public function getShop($slug)
    {
        $qb = $this->createQueryBuilder('cav')
                   ->leftJoin('cav.image', 'i')
                   ->addSelect('i')
                   ->leftJoin('cav.coordonnees', 'c')
                   ->addSelect('c')
                   ->leftJoin('cav.restaurant', 'cr')
                   ->addSelect('cr')
                    ->where('cav.slug = :slug')
                    ->setParameter('slug', $slug);

        $cr = $this->_em
                    ->getRepository('FBNGuideBundle:Coordonnees');

        $qb = $cr->joinCoord($qb);

        return $qb->getQuery()
                ->getOneOrNullResult();
    }
}
