<?php

// src/FBN/GuideBundle/DataFixtures/ORM/CoordinatesFRDept.php


namespace FBN\GuideBundle\DataFixtures\ORM;

//use Doctrine\Common\DataFixtures\FixtureInterface;
use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\OrderedFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use FBN\GuideBundle\Entity\CoordinatesFRDept as CoordFRDept;

class CoordinatesFRDept extends AbstractFixture implements OrderedFixtureInterface
{
    // Dans l'argument de la méthode load, l'objet $manager est l'EntityManager
    public function load(ObjectManager $manager)
    {
        $departments = array(
                        'Ain',
                        'Aisne',
                        'Allier',
                        'Alpes-de-Haute-Provence',
                        'Hautes-Alpes',
                        'Alpes-Maritimes',
                        'Ardèche',
                        'Ardennes',
                        'Ariège',
                        'Aube',
                        'Aude',
                        'Aveyron',
                        'Bouches-du-Rhône',
                        'Calvados',
                        'Cantal',
                        'Charente',
                        'Charente-Maritime',
                        'Cher',
                        'Corrèze',
                        'Corse-du-Sud',
                        'Haute-Corse',
                        'Côte-d\'Or',
                        'Côtes-d\'Armor',
                        'Creuse',
                        'Dordogne',
                        'Doubs',
                        'Drôme',
                        'Eure',
                        'Eure-et-Loir',
                        'Finistère',
                        'Gard',
                        'Haute-Garonne',
                        'Gers',
                        'Gironde',
                        'Hérault',
                        'Ille-et-Vilaine',
                        'Indre',
                        'Indre-et-Loire',
                        'Isère',
                        'Jura',
                        'Landes',
                        'Loir-et-Cher',
                        'Loire',
                        'Haute-Loire',
                        'Loire-Atlantique',
                        'Loiret',
                        'Lot',
                        'Lot-et-Garonne',
                        'Lozère',
                        'Maine-et-Loire',
                        'Manche',
                        'Marne',
                        'Haute-Marne',
                        'Mayenne',
                        'Meurthe-et-Moselle',
                        'Meuse',
                        'Morbihan',
                        'Moselle',
                        'Nièvre',
                        'Nord',
                        'Oise',
                        'Orne',
                        'Pas-de-Calais',
                        'Puy-de-Dôme',
                        'Pyrénées-Atlantiques',
                        'Hautes-Pyrénées',
                        'Pyrénées-Orientales',
                        'Bas-Rhin',
                        'Haut-Rhin',
                        'Rhône',
                        'Haute-Saône',
                        'Saône-et-Loire',
                        'Sarthe',
                        'Savoie',
                        'Haute-Savoie',
                        'Paris',
                        'Seine-Maritime',
                        'Seine-et-Marne',
                        'Yvelines',
                        'Deux-Sèvres',
                        'Somme',
                        'Tarn',
                        'Tarn-et-Garonne',
                        'Var',
                        'Vaucluse',
                        'Vendée',
                        'Vienne',
                        'Haute-Vienne',
                        'Vosges',
                        'Yonne',
                        'Territoire de Belfort',
                        'Essonne',
                        'Hauts-de-Seine',
                        'Seine-Saint-Denis',
                        'Val-de-Marne',
                        'Val-d\'Oise',
                        'Guadeloupe',
                        'Martinique',
                        'Guyane',
                        'La Réunion',
                        'Mayotte',
                        );

        $nums = array(
                    '1',
                    '2',
                    '3',
                    '4',
                    '5',
                    '6',
                    '7',
                    '8',
                    '9',
                    '10',
                    '11',
                    '12',
                    '13',
                    '14',
                    '15',
                    '16',
                    '17',
                    '18',
                    '19',
                    '2A',
                    '2B',
                    '21',
                    '22',
                    '23',
                    '24',
                    '25',
                    '26',
                    '27',
                    '28',
                    '29',
                    '30',
                    '31',
                    '32',
                    '33',
                    '34',
                    '35',
                    '36',
                    '37',
                    '38',
                    '39',
                    '40',
                    '41',
                    '42',
                    '43',
                    '44',
                    '45',
                    '46',
                    '47',
                    '48',
                    '49',
                    '50',
                    '51',
                    '52',
                    '53',
                    '54',
                    '55',
                    '56',
                    '57',
                    '58',
                    '59',
                    '60',
                    '61',
                    '62',
                    '63',
                    '64',
                    '65',
                    '66',
                    '67',
                    '68',
                    '69',
                    '70',
                    '71',
                    '72',
                    '73',
                    '74',
                    '75',
                    '76',
                    '77',
                    '78',
                    '79',
                    '80',
                    '81',
                    '82',
                    '83',
                    '84',
                    '85',
                    '86',
                    '87',
                    '88',
                    '89',
                    '90',
                    '91',
                    '92',
                    '93',
                    '94',
                    '95',
                    '971',
                    '972',
                    '973',
                    '974',
                    '976',
                        );

        $coordinatesFRArea_ids = array(
                                        23,
                                        8,
                                        24,
                                        26,
                                        26,
                                        26,
                                        23,
                                        7,
                                        21,
                                        7,
                                        25,
                                        21,
                                        26,
                                        11,
                                        24,
                                        19,
                                        19,
                                        10,
                                        22,
                                        27,
                                        27,
                                        12,
                                        18,
                                        22,
                                        20,
                                        16,
                                        23,
                                        9,
                                        10,
                                        18,
                                        25,
                                        21,
                                        21,
                                        20,
                                        25,
                                        18,
                                        10,
                                        10,
                                        23,
                                        16,
                                        20,
                                        10,
                                        23,
                                        24,
                                        17,
                                        10,
                                        21,
                                        20,
                                        25,
                                        17,
                                        11,
                                        7,
                                        7,
                                        17,
                                        14,
                                        14,
                                        18,
                                        14,
                                        12,
                                        13,
                                        8,
                                        11,
                                        13,
                                        24,
                                        20,
                                        21,
                                        25,
                                        15,
                                        15,
                                        23,
                                        16,
                                        12,
                                        17,
                                        23,
                                        23,
                                        6,
                                        9,
                                        6,
                                        6,
                                        19,
                                        8,
                                        21,
                                        21,
                                        26,
                                        26,
                                        17,
                                        19,
                                        22,
                                        14,
                                        12,
                                        16,
                                        6,
                                        6,
                                        6,
                                        6,
                                        6,
                                        1,
                                        2,
                                        3,
                                        4,
                                        5,
                                        );

        foreach ($nums as $i => $num) {
            $coordinatesfrdept[$i] = new CoordFRDept();
            $coordinatesfrdept[$i]->setNum($num);
        }

        foreach ($departments as $i => $department) {
            $coordinatesfrdept[$i]->setDepartment($department);

            $coordinatesfrdept[$i]->setCoordinatesFRArea($this->getReference('coordinatesfrarea-'.($coordinatesFRArea_ids[$i] - 1)));

            $this->addReference('coordinatesfrdept-'.$i, $coordinatesfrdept[$i]);

            $manager->persist($coordinatesfrdept[$i]);
        }

        $manager->flush();
    }

    public function getOrder()
    {
        return 2; // l'ordre dans lequel les fichiers sont chargés
    }
}
