fbn_user_profile_edit_change_password:
    path:  /edit-all
    defaults: { _controller: FBNUserBundle:User:editProfileChangePassword }

fbn_user_profile_delete:
    path:  /delete
    defaults: { _controller: FBNUserBundle:User:deleteUser }